version: '3'
services:
  expressions-web:
    image: bkauf/expressions-web
    volumes:
      - expressions:/expressions
    ports:
      - "9000:8080"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.expression == yes
  expressions-engine:
    depends_on:
       - expressions-web
    image: bkauf/expressions-engine
    volumes:
       - expressions:/expressions
       - /var/run/docker.sock:/var/run/docker.sock
       - /usr/bin/docker:/usr/bin/docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.expression == yes
volumes:
    expressions:
      external: true
